version: '2.4'
# Use version 2.4 for mem_limit setting. Version 3+ uses deploy.resources.limits.memory
# instead, but that only works for swarm with docker-compose 1.25.1.

services:
  mq:
    image: rabbitmq:3-alpine
    user: '${RABBITMQ_UID:-499:499}'
    hostname: datatracker-mq
#    deploy:
#      resources:
#        limits:
#          memory: 1gb # coordinate with settings in rabbitmq.conf
#        reservations:
#          memory: 512mb
    mem_limit: 1gb  # coordinate with settings in rabbitmq.conf
    ports:
      - '${MQ_PORT:-5672}:5672'
    volumes:
      - ./lib.rabbitmq:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/conf.d/90-ietf.conf
      - ./definitions.json:/ietf-conf/definitions.json
    restart: unless-stopped
    logging:
      driver: "syslog"
      options:
        syslog-address: 'unixgram:///dev/log'
        tag: 'docker/{{.Name}}'
#        syslog-address: "tcp://ietfa.amsl.com:514"

  celery:
    image: ghcr.io/ietf-tools/datatracker-celery:latest
    environment:
      CELERY_APP: ietf
      # UPDATE_REQUIREMENTS: 1  # uncomment to update Python requirements on startup
    command:
      - '--loglevel=INFO'
    user: '${CELERY_UID:-499:499}'
    volumes:
      - '${DATATRACKER_PATH:-..}:/workspace'
      - '${MYSQL_SOCKET_PATH:-/run/mysql}:/run/mysql'
    depends_on:
      - mq
    network_mode: 'service:mq'
    restart: unless-stopped
    logging:
      driver: "syslog"
      options:
        syslog-address: 'unixgram:///dev/log'
        tag: 'docker/{{.Name}}'
#        syslog-address: "tcp://ietfa.amsl.com:514"
