name: PR - Run All Tests

on:
  pull_request:
    branches:
      - 'main'
      - 'feat/rfc'
    paths:
      - 'client/**'
      - 'ietf/**'
      - 'playwright/**'
      - 'requirements.txt'
      - 'package.json'

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
    with:
      ignoreLowerCoverage: false